apiVersion: v1
kind: Service
metadata:
  name: rust-service

spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: sample-rust-service
